#Experiment parameters
random_seed: 13
notes: "CAN bus pre-training run"

encoder_type: "patchTST"

# Encoder parameters
task_name: "pretraining" 

# Model parameters
model_name: "TraceEncoder"
seq_len_channel: 300
patch_len: 6
patch_stride_len: 6
revin_affine: False
d_model: 384    #384, 768 or 1024
dropout: 0.1
n_heads: 6
e_layers: 6
attention_dropout: 0.1
torch_dtype: "bfloat16"
value_embedding_bias: False # Whether to add biases to the value embeddings
orth_gain: 1.41
pos_embed_type: "rel_pos" # "rope" or "rel_pos" add positional embedding to the input
set_input_mask: True # Whether to set the input mawsk
output_attention: False # Whether to output the attention weights
activation: 'gelu'      # "gelu" or "relu"
flash_attention: False
# transformer_type: "encoder_only" # "encoder_decoder" "encoder_only" "decoder_only"
# transformer_backbone: 'google/flan-t5-large' # "PatchTST" "google/flan-t5-base" "t5-large"
# freeze_transformer_backbone: False # Whether to freeze the transformer backbone

# Logging
log_interval: 1
checkpoint_interval: 1
debug: False

# Training parameters
train_batch_size : 256 # 1024 2048 3072 4096
val_batch_size: 256 # 1024 2048 3072 4096 
mask_ratio: 0.3
max_epoch: 200
optimizer_name : "AdamW"
enable_gradient_checkpointing: True
max_norm: 5
weight_decay: 0.05
lr_scheduler_type: 'linearwarmupcosinelr'
init_lr: 0.0001 # 1e-4
min_lr: 0.00001 # 1e-5
lr_decay_rate: 0.9
warmup_lr: 0.00001 # 1e-5
warmup_steps: 1000
use_amp: True
classification_label_smoothing: 0.05
beta: 0.2
distributed: True
early_stop: False
patience: 100
delta: 0.0001



# Dataset parameters
n_channels: 6
num_class: 13
scale : True
upsampling_pad_direction : "backward"
upsampling_type : "pad"
downsampling_type : "interpolate"
pad_mode : "constant"
pad_constant_values : 0
shuffle : True
num_workers : 5
pin_memory : True
drop_last : False